#!/usr/bin/env bash
## CSI Linux apktool installer / launcher
## bash ./apktoolrun

source /opt/csitools/sharedfunctions

if ! which apktool > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install apktool -y
fi

file="$(zenity --file-selection --title='Select an APK File to export')"
case $? in
           0)
           	_Check-Case
           	apkname=$(basename $file)
                apktool d $file -o Export/$apkname -f
                Thunar Export/$apkname;;
           1)
                apktool --help;;
          -1)
                echo "An unexpected error has occurred."; exit;;
esac

exit
