#!/usr/bin/env bash
## CSI Linux AutoRecon installer / launcher
## bash ./autoreconrun


if ! command -v pipx &> /dev/null
then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install -y python3-venv
	python3 -m pip install --upgrade pip
	python3 -m pip install --user pipx
	python3 -m pipx ensurepath
fi

if ! command -v pipx &> /dev/null
then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	cd usr/share/
	echo $key | sudo -S apt update
	echo $key | sudo -S git clone https://github.com/danielmiessler/SecLists.git
	echo $key | sudo -S mv SecLists/ seclists/
	echo $key | sudo -S apt install curl enum4linux feroxbuster impacket-scripts nbtscan nikto nmap onesixtyone oscanner redis-tools smbclient smbmap snmp sslscan sipvicious tnscmd10g whatweb wkhtmltopdf

fi

