#!/usr/bin/env bash
## CSI Linux autotimeline installer / launcher
## bash ./autotimelinerun


red=`tput setaf 1`
reset=`tput sgr0`
printf "Welcome to the Autotimeliner Memory App\n"
timestamp=$(date +%Y-%m-%d:%H:%M)
closecase=$(date +%Y%m%d%H%M)

source /opt/csitools/sharedfunctions

Menu() {

	if [ ! -f  /opt/autotimeliner/autotimeliner.py ]; then
		key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
		echo "Installing AutoTimeliner"
		cd /opt
		echo $key | sudo -S git clone https://github.com/andreafortuna/autotimeliner.git
		echo $key | sudo -S chown csi:csi autotimeliner -R
		cd autotimeliner
		ls
	fi

	python3 /opt/autotimeliner/autotimeline.py -h
	exit
}

if [ -z "$1" ]
then
	echo "Fresh Run"
	trap finish EXIT
else
	echo "$1 passed"
fi

export -f _wifissid _wifibssid

StartCase "$1"
echo "Case=$cases"
Menu
