#!/usr/bin/env bash
## CSI Linux binwalk installer / launcher
## bash ./binwalkrun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	
if ! which binwalk > /dev/null; then
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install binwalk -y
fi
binwalk -h
exit

