#!/usr/bin/env bash
## CSI Linux ddrescue-gui installer / launcher
## bash ./ddrescue-guirun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	
if ! which ddrescue-gui > /dev/null; then
	cd /tmp
	wget https://csilinux.com/downloads/ddrescue-gui.deb
	echo $key | sudo -S apt ./install ddrescue-gui.deb -y
	cd ~/Documents/Tools
	wget https://www.hamishmb.com/html/Docs/ddrescue-gui.pdf
fi
echo $key | sudo -S ddrescue-gui -h
exit

