#!/usr/bin/env bash
## CSI Linux Claim AV & GUI installer / launcher
## bash ./lmd

if ! command -v discord &> /dev/null
then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt install snap snapd -y
	echo $key | sudo -S snap install discord 
fi

discord
