#!/usr/bin/env bash
## CSI Linux dnsrecon installer / launcher
## bash ./dnsreconrun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	
if ! which dnsrecon > /dev/null; then
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install dnsrecon -y
fi
dnsrecon -y
exit

