#!/usr/bin/env bash
## CSI Linux Docker installer / launcher
## bash ./dockerrun

if ! which docker > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt install docker docker.io containerd runc -y #| zenity --progress --pulsate --text="Downloading and Installing Dependencies" --auto-close
fi
docker
exit

