#!/usr/bin/env bash
##install Exodus


if ! command -v exodus &> /dev/null
then
	key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400) || exit
	cd /tmp
	wget https://www.csilinux.com/downloads/exodus_21.3.2_amd64.deb
	echo $key | sudo -S dpkg -i exodus_21.3.2_amd64.deb
fi
exodus
