#!/usr/bin/env bash
## CSI Linux FinalRecon installer / launcher
## bash ./finalreconrun

if [ ! -f /opt/FinalRecon/finalrecon.py ]; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo "Installing FullRecon"
	cd /opt
	echo $key | sudo -S git clone https://github.com/thewhiteh4t/FinalRecon.git
	echo $key | sudo -S chown csi:csi FinalRecon -R
	cd FinalRecon
	echo "Installing FullRecon requirements.  This may take a few minutes..."
	pip3 install -r requirements.txt > /dev/null 2>&1
	echo "FullRecon requirements complete"
fi

cd /opt/FinalRecon/
python3 /opt/FinalRecon/finalrecon.py
exit
