#!/usr/bin/env bash
## CSI Linux Forensic Registry EDitor (fred) installer / launcher
## bash ./


	
if ! which fred > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install fred fred-reports
fi
fred
exit

