#!/usr/bin/env bash
## CSI Linux guymager installer / launcher
## bash ./guymagerrun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	
if ! which guymager > /dev/null; then
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install guymager -y
fi
echo $key | sudo -S guymager
exit

