#!/usr/bin/env bash
## CSI Linux nikto installer / launcher
## bash ./niktorun


if ! command -v nikto &> /dev/null
then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install nikto -y
fi

nikto -update
clear
nikto -Help
