#!/usr/bin/env bash
## CSI Linux KVM/Virt-manager installer / launcher
## bash ./kvmrun


key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
if ! which virt-manager > /dev/null; then
	echo $key | sudo -S apt update #| zenity --progress --pulsate --text="Updating Repos" --auto-close
	echo $key | sudo -S apt install qemu-kvm libvirt-bin ubuntu-vm-builder libvirt-daemon-system libvirt-clients bridge-utils -y #| zenity --progress --pulsate --text="Downloading and Installing Dependencies" --auto-close
	echo $key | sudo adduser ‘csi’ libvirt
	echo $key | sudo adduser ‘csi’ kvm
	echo $key | sudo -S systemctl enable --now libvirtd
	echo $key | sudo -S apt install virt-manager -y #| zenity --progress --pulsate --text="Downloading and Installing Virt-Manager" --auto-close
fi
echo $key | sudo -S virt-manager
exit
