#!/usr/bin/env bash
## CSI Linux lxd installer / launcher
## bash ./lxdrun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	
if ! which lxc > /dev/null; then
	echo $key | sudo -S xterm -e apt install lxd -y #| zenity --progress --pulsate --text="Downloading and Installing Dependencies" --auto-close
	echo $key | sudo -S adduser csi lxd
	newgrp lxd
	lxc list
	echo $key | sudo -S lxd init
fi
	echo $key | sudo -S lxc profile show default
	exit
