#!/usr/bin/env bash
## CSI Linux lynis installer / launcher
## bash ./lynisrun

if ! which lynis > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt-get install lynis -y
fi
echo $key | sudo -S lynis -h
exit
