#!/usr/bin/env bash
## CSI Linux sn0int installer / launcher
## bash ./sn0intrun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)

if ! sudo which maldet > /dev/null; then
	echo "Installing Maldetect"
	cd /tmp
	wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
	tar -xvf maldetect-current.tar.gz
	cd maldetect-1.6.4/
	echo $key | sudo -S ./install.sh
fi

maldet
exit	
