#!/usr/bin/env bash
## CSI Linux msfconsole installer / launcher
## bash metasploitrun


if ! command -v msfconsole &> /dev/null
then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	cd /tmp
	wget http://downloads.metasploit.com/data/releases/metasploit-latest-linux-x64-installer.run
	echo $key | sudo -S chmod +x metasploit-latest-linux-x64-installer.run
	echo "This may take a while to set up the service..."
	echo $key | sudo -S ./metasploit-latest-linux-x64-installer.run	
fi

clear
echo "Running Metasploit Console"
msfconsole


