#!/usr/bin/env bash
## CSI Linux Shodan CLI installer / launcher
## bash ./shodanrun

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	
if ! which shodan ]] > /dev/null; then
	sudo easy_install shodan
fi
shodan -h
exit

