#!/usr/bin/env bash
## CSI Linux slack installer / launcher
## bash ./slack
	
if ! which slack > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo apt update
	echo $key | sudo apt install slack -y
fi
slack
exit
