#!/usr/bin/env bash
## CSI Linux spiderpig installer / launcher
## bash ./spiderpigrun

if [ ! -f /opt/Spiderpig/spiderpig.rb ]; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo "Installing SpiderPig"
	cd /opt
	echo $key | sudo -S git clone https://github.com/hatlord/Spiderpig.git
	echo $key | sudo -S chown csi:csi Spiderpig -R
	cd Spiderpig
	echo $key | sudo -S bundle install
fi

cd /opt/Spiderpig
./spiderpig.rb -h
exit
