#!/usr/bin/env bash
## CSI Linux tiktok-scraper installer / launcher
## bash ./tiktokscraperrun

red=`tput setaf 1`
reset=`tput sgr0`
printf "Welcome to the Social Media Search App\n"
timestamp=$(date +%Y-%m-%d:%H:%M)
closecase=$(date +%Y%m%d%H%M)

source /opt/csitools/sharedfunctions

Menu() {
	if ! which tiktok-scraper > /dev/null; then
		key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
		echo "Installing node-pre-gyp"
		npm install node-pre-gyp > /dev/null 2>&1
		echo $key | sudo -S npm install canvas > /dev/null 2>&1
		echo $key | sudo -S mkdir /usr/local/lib/node_modules > /dev/null 2>&1
		echo $key | sudo -S mkdir /usr/local/lib/node_modules/tiktok-scraper > /dev/null 2>&1
		echo $key | sudo -S mkdir /usr/local/lib/node_modules/tiktok-scraper/node_modules > /dev/null 2>&1
		echo $key | sudo -S mkdir /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas > /dev/null 2>&1
		echo "Installing TikTok Scraper"
		echo $key | sudo -S mkdir /usr/local/lib/node_modules/tiktok-scraper/node_modules/canvas/.node-gyp > /dev/null 2>&1
		echo $key | sudo -S npm i -g tiktok-scraper > /dev/null 2>&1
		echo $key | sudo -S chown csi:csi /usr/local/lib/node_modules -R
		echo "Installing TickTok Scraper..."
		npm i -g tiktok-scraper > /dev/null 2>&1
		echo $key | sudo -S chown csi:csi /usr/local/bin/tiktok-scraper -R
	fi
	_tiktokscraper
}


_tiktokscraper() {
	handle=$(zenity --entry --title "TikTok Scraper" --text "Enter username to search for" 2> >(grep -v 'GtkDialog' >&2))   
	if [ -n "$handle" ]; then
		echo "0-- Attempting to pull data for $handle --0"
		_stopwatch; echo "$stopwatch: Running CSI TikTok-Scraper." >> ~/Cases/$cases/audit.log
		mkdir ~/Cases/$cases/Videos/TikTok
		tiktok-scraper user $handle -d -n 100 --session sid_tt=dae32131231 --historypath ~/Cases/$cases/Videos/TikTok/ --filepath ~/Cases/$cases/Videos/TikTok/ |tee >(zenity --progress --pulsate --no-cancel --auto-close --text="Please wait...")
	else
	  	zenity --error --text "No handle entered, exiting" 2> >(grep -v 'GtkDialog' >&2)
		exit
	fi
}

if [ -z "$1" ]
then
	echo "Fresh Run"
	trap finish EXIT
else
	echo "$1 passed"
fi

export -f _wifissid _wifibssid

StartCase "$1"
echo "Case=$cases"
Menu
