#!/usr/bin/env bash
## CSI Linux trape installer / launcher
## bash ./traperun

if [[ ! -f /opt/dradis-ce/LICENSE.txt ]]; 
then
	cd /opt
	git clone https://github.com/jofpin/trape.git
	cd trape
	pip3 install -r requirements.txt
	python3 trape.py -h
fi

cd /opt/trape
python3 trape.py -h
echo "Example: python3 trape.py -h
