#!/usr/bin/env bash
## CSI Linux upx installer / launcher
## bash ./upxrun

if ! which upx > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt-get install upx -y
fi
upx --help	
exit
