#!/usr/bin/env bash
## CSI Linux viper installer / launcher
## bash ./viperrun

if ! which viper > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400); echo $key
	echo $key | sudo -S apt-get install gcc python-socks libssl-dev swig p7zip-full unrar ssdeep libfuzzy-dev tor clamav-daemon unrar -qq
	echo $key | sudo -S service clamav-freshclam stop
	echo $key | sudo -S freshclam
	echo $key | sudo -S service clamav-freshclam start
	pip3 install -U tox-travis
	pip3 install -e .
	echo "update-modules" > /tmp/viper
	echo $key | sudo -S viper < /tmp/viper
	echo $key | sudo -S service clamav-daemon restart
	python3 -m pip install viper-framework
fi
viper
exit
