#!/usr/bin/env bash
# CSI Linux WhatsDesk - WhatsApp installer / launcher
# bash ./whatsapp

if ! which whatsdesk > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	notify-send 'Installing' 'Installing WhatsDesk.  This may take some time.  If the installation is successful, the program will open up.'
	echo $key | sudo -S snap install whatsdesk
fi
notify-send 'Running' 'WhatsDesk should open soon.'
whatsdesk
