#!/usr/bin/env bash
## CSI Linux wxhexeditor installer / launcher
## bash ./wxhexeditorrun


if ! which wxHexEditor > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install wxhexeditor -y
fi
wxHexEditor
exit

