#!/usr/bin/env bash
## CSI Linux Claim AV & GUI installer / launcher
## bash ./lmd

key=$(zenity --password --title "Enter you SUDO password to start the install." --text "Enter you SUDO password." --width 400)

if ! command -v yersinia &> /dev/null
then
	
	echo $key | sudo -S apt update
	echo $key | sudo -S apt install yersinia -y
fi

echo $key | sudo -S yersinia -G
