#!/usr/bin/env bash


key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400)
timedatectl
echo $key | sudo -S timedatectl set-timezone Asia/Kolkata
echo "---"
echo "Your time now"
timedatectl


