#!/usr/bin/env bash
##CSI Cases Menu Script by CSI Linux v2021.1.24.5
##tools@csilinux.com - Jeremy Martin - infosecwriter

#define choices
opt1="Update CSI Linux"
opt2="Update CSI Tools"
opt3="Manage APIs in certain applications"
opt4="Move Cases Folder"
opt99="Exit"
timestamp=$(date +%Y-%m-%d:%H:%M)
closecase=$(date +%Y%m%d%H%M)
fqdnregex="\b((xn--)?[a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}\b"

source /opt/csitools/sharedfunctions

Menu () {
csimenu=$(zenity --list --title "CSI Case Management Menu" --text "The CSI Case Management System allows you to manage the case or run\ninvestigation tools.  What would you like to do?" --width=350 --height=250 --radiolist \
	--column "Pick" --column "Option" \
	TRUE "$opt1" \
	FALSE "$opt2" \
	FALSE "$opt3" \
	FALSE "$opt4" \
	FALSE "$opt99" \
	2> >(grep -v 'GtkDialog' >&2)) 

echo "Pick your option to run..."
_stopwatch; echo "$stopwatch: CSI Case Management Menu." >> ~/Cases/$cases/audit.log
case $csimenu in			
	
	$opt1 ) #Update CSI
		/opt/csitools/powerup
		Menu
	;;
	
	$opt2 ) #Update CSI tools
		key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400)
		cd /tmp
		echo "Installing CSI Linux Tools and Menu update"
		rm csi*
		wget https://csilinux.com/downloads/csitools22.zip
		mv csitools22.zip csitools.zip
		echo $key | sudo -S unzip -o -d / csitools.zip
		echo $key | sudo -S chown csi:csi -R /opt/csitools 
		echo $key | sudo -S chmod +x /opt/csitools/* -R
		Menu
	;;
	
	$opt3 ) #Manage APIs
		#Run Tool
		/opt/csitools/manageapis
		Menu
	;;	
	
	$opt4 ) #Move the Cases folder
		#Run Tool
		xterm -e /opt/csitools/managecasefolder
		Menu
	;;
			
		
		
	$opt99 ) #Exit
		if ! which wmctrl > /dev/null; then
		   sudo apt-get install wmctrl
		fi
		wmctrl -r "Terminal" -b add,shaded
		exit
	;;
	*) echo "$0: unknown option specified: " >&2
	exit
esac
}

trap finish EXIT

Menu

