#!/usr/bin/env bash

##YouTube DL

source /opt/csitools/sharedfunctions

url=$(zenity --entry --title "Video Downloader" --text "Enter target URL" --entry-text "" 2> >(grep -v 'GtkDialog' >&2))

if [ -n "$url" ]; then

	youtube-dl "$url" -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "$url" -o /home/csi/Video_Utilities/Youtube-DL/"$timestamp%(title)s.%(ext)s" -i | zenity --progress --pulsate --no-cancel --auto-close --title="Video Downloader" --text="Video being saved to /home/csi/Video_Utilities/Youtube-DL/" 2> >(grep -v 'GtkDialog' >&2)

	sleep 2

	nautilus /home/csi/Video_Utilities/Youtube-DL/ >/dev/null 2>&1

else
	zenity --error --text "Missing URL, exiting"
   	exit
fi 

