#!/usr/bin/env bash
# EyeWitness GUI for CSI Linux

StartCase() {
	printf "Enter the case name\n"
	cases=$(zenity --entry --width=300 --title "Case Name" --text "Enter the case to add this to:" 2> >(grep -v 'GtkDialog' >&2))
	if [ -n "$cases" ]; then
		if [ ! -d "~/Cases/$cases" ]; then
		   	mkdir ~/Cases/$cases 2>/dev/null 
			cd ~/Cases/$cases
		fi 	
	else
	  	zenity --error --width=200 --text "No case entered, exiting" 2> >(grep -v 'GtkDialog' >&2)
		exit
	fi
}

StartCase

		#define choices
		eopt1="Single URL"
		eopt2="Multiple URLs (use file)"
		eyewitness=$(zenity  --list  --title "EyeWitness" --text "Do you want to grab one or multiple URLs?" --width=400 --height=200 --radiolist  --column "Choose" --column "Option" TRUE "$eopt1" FALSE "$eopt2" 2> >(grep -v 'GtkDialog' >&2))
		case $eyewitness in
       			$eopt1 ) #Single
			domain=$(zenity --entry --title "EyeWitness" --text "Enter target URL (ex: https://www.google.com)" --entry-text "" 2> >(grep -v 'GtkDialog' >&2))
			
			if [ -n "$domain" ]; then
				cd /opt/EyeWitness
				mkdir ~/Cases/$cases/$domain 2>/dev/null
				targetdomain="$(echo "$domain" | sed -e 's/https:\/\///g; s/http:\/\///g')"
				/opt/EyeWitness/Python/EyeWitness.py --web  --timeout=120 --single $domain -d ~/Cases/$cases/$targetdomain
			else
				zenity --error --width=200 --text "No URL entered, exiting" 2> >(grep -v 'GtkDialog' >&2)
				exit
			fi
			sleep 10
			;;
			$eopt2 ) #Multiple
			eyewitness_file=$(zenity --file-selection --title "URL List" --text "Add List of URLs (line separated)" 2> >(grep -v 'GtkDialog' >&2))
			if [ -n "$eyewitness_file" ]; then
				./EyeWitness.py --web -f "$eyewitness_file" -d ~/Cases/$cases/$timestamp
			else
				zenity --error --width=200 --text "No file found, exiting" 2> >(grep -v 'GtkDialog' >&2)
				exit
			fi
		esac
