#!/usr/bin/env bash

key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400)

command=$(zenity --entry --title "Enter the command to run" --text "Enter the command to run" --width 600)
echo $command
echo $key | sudo -S $command

