#!/usr/bin/env bash
##check for and install Maltego

if ! which maltego > /dev/null; then
	key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400)
	cd /tmp
	wget https://csilinux.com/downloads/Maltego.deb
	echo $key | sudo -S dpkg -i Maltego.deb
fi

maltego
