#!/usr/bin/env bash
# occli GUI for CSI Linux

Startoccli() {
	printf "Enter the case name\n"
	if [ -z "$1" ]
	then
		cases=$(zenity --entry --width=300 --title "Case Name" --text "Enter the case to add this to:" 2> >(grep -v 'GtkDialog' >&2))
	else
	      	cases=$1
	      	echo "Adding to Case $cases"
	fi	

	if [ -n "$cases" ]; then
		if [ ! -d "~/Cases/$cases" ]; then
		   	mkdir ~/Cases/$cases 2>/dev/null
			cd ~/Cases/$cases
		fi 	
		/opt/csitools/case_env $cases 2>/dev/null
	else
	  	zenity --error --width=200 --text "No case entered, exiting" 2> >(grep -v 'GtkDialog' >&2)
		exit
	fi
}

Startoccli $1

comp=$(zenity --entry --title "occli" --text "Enter target company name" --entry-text "" 2> >(grep -v 'GtkDialog' >&2))
mkdir ~/Cases/$cases/Export/$domain 2>/dev/null
occli -q "$comp" -d "/home/csi/Cases/$cases/Export/$comp.txt" -v
gedit "/home/csi/Cases/$cases/Export/$comp.txt"
exit
