#!/bin/bash
trap 'printf "\n";exit 1' 2
mkdir ~/Cases/$1 2>/dev/null
filename=~/Cases/$1/Export/phone_Search_$2.txt

testuser() {
	printf "\e[1;77m[\e[0m\e[1;92m+\e[0m\e[1;77m] $sitename: \e[0m"
	check1=$(curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0" -i $sitetest -H "Accept-Language: en" -L -s | grep "$stringtest" ; echo $?)
	if [[ $userfound == *'1'* ]] ; then 
		if [[ $check1 == *'1'* ]] ; then 
			printf "\e[1;93mNot Found!\e[0m\n" 
		elif [[ $check1 == *'0'* ]]; then 
			printf "\e[1;92m Found!\e[0m $sitetest\n" $2
			printf "$sitetest\n" $2 >> $filename
		fi
	elif [[ $userfound == *'0'* ]]; then 
		if [[ $check1 == *'0'* ]] ; then 
			printf "\e[1;93mNot Found!\e[0m\n" 
		elif [[ $check1 == *'1'* ]]; then 
			printf "\e[1;92m Found!\e[0m $sitetest\n" $2
			printf "$sitetest\n" $2 >> $filename
		fi
	fi
}

clear
printf "\n"
printf "\e[1;93m    .:.:.\e[0m\e[1;77m CSI Linux Phone Number Search - csilinux.org   \e[0m\e[1;93m.:.:.\e[0m\n"
printf "\n"
printf "  \e[101m\e[1;77m:: Disclaimer: Developers assume no liability and are not    ::\e[0m\n"
printf "  \e[101m\e[1;77m:: responsible for any misuse or damage caused by user...    ::\e[0m\n"
printf "  \e[101m\e[1;77m:: Verify findings.  There may be false positives/negatives. ::\e[0m\n"
printf "\n"
echo "Searching for the Username:  " $2
printf "\n"

if [[ -e $filename ]]; then
printf "\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Removing previous file:\e[0m\e[1;77m %s.txt" $filename
rm -rf $filename
fi
printf "\n"
printf "\e[1;92m[\e[0m\e[1;77m*\e[0m\e[1;92m] Checking username\e[0m\e[1;77m %s\e[0m\e[1;92m on: \e[0m\n" $2

touch $filename

## Phone Number Check
sitename="SmartBackgroundChecks"
sitetest="https://www.smartbackgroundchecks.com/phone/$2"
stringtest="HTTP/2 404\|Not Found"
userfound="0"
testuser

sitename="PeopleFinder"
sitetest="https://www.peoplefinder.com/reverse-phone-search/$2"
stringtest="sorry\|any results|\was found in"
userfound="0"
testuser

sitename="Zabasearch"
sitetest="https://www.zabasearch.com/phone/$2"
stringtest="Found 0  Results"
userfound="0"
testuser

sitename="Intelius"
sitetest="https://www.intelius.com/reverse-phone-lookup/$2"
stringtest="HTTP/2 404\|Not Found"
userfound="0"
testuser

sitename="WhitePages"
sitetest="https://www.whitepages.com/phone/$2"
stringtest="HTTP/2 404\|Not Found"
userfound="0"
testuser

## Dump Report
echo "Phone Number: $2" >> ~/Cases/$1/Export/PhoneNumbers.txt
cat ~/Cases/$1/Export/PhoneNumbers.txt | sort -u > acctemp.tmp
mv acctemp.tmp ~/Cases/$1/Export/PhoneNumbers.txt

if zenity --question --text="Would you like to open the findings in a browser?"; then
	while read links; do 
	    echo "Opening: $links"; screen -d -m google-chrome-stable $links
	done < $filename
	echo "Please wait for Chrome to open..."
else
	echo "Done."
fi  
