#!/usr/bin/env bash
# Photon GUI for CSI Linux

StartCase() {
	printf "Enter the case name\n"
	cases=$(zenity --entry --width=300 --title "Case Name" --text "Enter the case to add this to:" 2> >(grep -v 'GtkDialog' >&2))
	if [ -n "$cases" ]; then
		if [ ! -d "~/Cases/$cases" ]; then
		   	/opt/csitools/case_env $cases 2>/dev/null 
			cd ~/Cases/$cases
		fi 	
	else
	  	zenity --error --width=200 --text "No case entered, exiting" 2> >(grep -v 'GtkDialog' >&2)
		exit
	fi
}

StartCase

domain=$(zenity --entry --title "Metagoofil" --text "Enter target domain name" --entry-text "" 2> >(grep -v 'GtkDialog' >&2))
		mkdir ~/Cases/$cases/Export/$domain 2>/dev/null
		python3 /opt/Photon/photon.py -u $domain --wayback --clone --keys -l 10 -t 100 --dns -o ~/Cases/$cases/Export/$domain/

