#!/bin/bash
# reset a network adapter with dhcp
# csi@csi : resetnic

if [ -z "$1" ]
then
      	key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400) || exit
else
      echo "key is set"
	key=$1
fi

#test=$(ifconfig enp0s8 | grep 10.152.152.11); echo $test
ifconfig -a

if [ -z "$2" ]
then
	adapt=$(zenity --list --radiolist --column="Pick" --column="Network Adapter" TRUE $(ifconfig -a | grep flags | sed -e "s/:/\ FALSE\ :/g"| cut -d: -f1) --mid-search --height=185 --width=250 2> >(grep -v 'GtkDialog' >&2)) || exit
else
	echo "Adapter is set to $2"
	adapt=$2
fi

echo $key | sudo -S  ip link set $adapt down
echo $key | sudo -S  ip link set $adapt up

echo $key | sudo -S  dhclient $adapt

ifconfig $adapt
