#!/usr/bin/env python3

import requests
import time
import subprocess



num = 0
#imagenum = input("Number of images to generate: ")

for request in range(int(1)):
    num += 1
    url = "https://thispersondoesnotexist.com/image"
    r = requests.get(url, allow_redirects=True)
    open("image-{0}.png".format(num), "wb").write(r.content)
    print("image-{0}.png complete".format(num))
    filename="image-{0}.png".format(num)
    args = ["ristretto", "image-{0}.png".format(num)]
    time.sleep(1) #time between requests
    
subprocess.run(args) 
