#!/bin/bash
trap 'printf "\n";exit 1' 2

if [ -z "$1" ]
then
      key=$(zenity --password --title "Enter you SUDO password." --text "Enter you SUDO password." --width 400); echo $key
else
      echo "key is set"
	key=$1
fi

echo $key | sudo -S sudo service libvirt-guests start
echo $key | sudo -S sudo service libvirtd start
echo $key | sudo -S virt-manager
conky -o -a top_right

