#!/bin/sh
awk --assign M="${1:?Month}" --assign D="${2:?Day}" '
    M == $1 && D >= $2  || M == $3 && D <= $4 {
        print $5
        found = 1
        exit
    }
    END {
        if (!found) {
            exit 1
        }
    }
' <<EOF
    3   21  4   19  Aries
    4   20  5   20  Taurus
    5   21  6   20  Gemini
    6   21  7   22  Cancer
    7   23  8   22  Leo
    8   23  9   22  Virgo
    9   23  10  22  Libra
    10  23  11  21  Scorpio
    11  22  12  21  Sagittarius
    12  22  1   19  Capricorn
    1   20  2   18  Aquarius
    2   19  3   20  Pisces
EOF
